import { z } from "zod";

export const lpgTankerSchema = z.object({
  month: z.string().min(1, "Month is required"),
  year: z.string().min(1, "Year is required"),
  vehicleId: z.number().int().positive(),
  serialNo: z.number().int().positive(),
  date: z.string().or(z.date()),
  tripId: z.string().min(1, "Trip ID is required"),
  driverId: z.number().int().positive(),
  loadingPlantId: z.number().int().positive(),
  deliveryLocationId: z.number().int().positive(),
  loadQuantityPerTon: z.number(),
  km: z.number(),
  fastag: z.number(),
  tripStartDate: z.string().or(z.date()),
  tripEndDate: z.string().or(z.date()),
  unloadQuantityPerTon: z.number(),
  shortage: z.number(),
  wayExpense: z.number(),
  others: z.number(),
  dieselGiven: z.number(),
  excessDiesel: z.number(),
  dieselAmount: z.number(),
  advance: z.number(),
  totalExpense: z.number(),
  ratePerTon: z.number(),
  freight: z.number(),
});
